# Generated by Django 4.0 on 2022-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_cars_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='rating'),
        ),
    ]
